[package]
name = "libsml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsml-sys = { path = "../libsml-sys" }
